"""empty message

Revision ID: a0c2313c0387
Revises: 012958d1023f
Create Date: 2016-03-31 16:25:21.781303

"""

# revision identifiers, used by Alembic.
revision = 'a0c2313c0387'
down_revision = '012958d1023f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('text', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('response_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], [u'question.id'], name=u'answer_ibfk_1', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], [u'response.id'], name=u'answer_ibfk_2', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('question_answer')
    ### end Alembic commands ###
