"""empty message

Revision ID: cdc695a55570
Revises: f2c915d8394d
Create Date: 2016-04-11 11:59:00.766137

"""

# revision identifiers, used by Alembic.
revision = 'cdc695a55570'
down_revision = 'f2c915d8394d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'form', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form', type_='foreignkey')
    op.drop_column('form', 'user_id')
    ### end Alembic commands ###
