"""empty message

Revision ID: f2c915d8394d
Revises: f3f8bac7ba1c
Create Date: 2016-04-11 10:39:12.800400

"""

# revision identifiers, used by Alembic.
revision = 'f2c915d8394d'
down_revision = 'f3f8bac7ba1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    ### end Alembic commands ###
